#!/bin/bash
SCRIPT_DIR=$(dirname "$0")
cmake $SCRIPT_DIR -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_PYTHON=ON -DENABLE_BEDROCK=ON -DENABLE_LEVELDB=ON -DENABLE_ROCKSDB=ON -DENABLE_BERKELEYDB=ON -DENABLE_TKRZW=ON -DENABLE_LMDB=ON -DENABLE_GDBM=ON -DENABLE_UNQLITE=ON -DENABLE_LUA=ON -DENABLE_YCSB=OFF -DENABLE_REMI=ON
